project:
  type: website

website:
  title: "Geospatial Community"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/geocommunity/geocommunity_blog
      # - icon: twitter
      #   href: https://twitter.com
  favicon: turkeypin.svg
format:
  html:
    theme: litera
    css: styles.css

editor: visual

